/* parse the tap file that is generated by prg2wav */

#include <stdio.h>
#include <assert.h>

#define LPULSE 0x55
#define MPULSE 0x43
#define SPULSE 0x30

enum sig_type {
    PILOT, ZERO, ONE, NEWDM, ENDDM
};

int parity(int x)
{
    int p = 0;
    while (x) {
        p ^= x & 1;
        x = x >> 1;
    }
    return p;
}

int main()
{
    FILE *fp;
    char buf[64];

    int prev = -1, curr = -1;

    fp = fopen("hello4.tap","rb");
    fseek(fp, 20, SEEK_SET);
    while (fread(buf, 1, 2, fp) == 2) {
        if (buf[0] == SPULSE && buf[1] == SPULSE) {
            unsigned long a = ftell(fp) - 2;
            curr = PILOT;
            if (prev != PILOT)
                printf("%08lx pilot tone\n", a);
        } else if (buf[0] == LPULSE && buf[1] == MPULSE) {
            int b = 0;
            int p = 0;
            unsigned long a = ftell(fp);
            curr = NEWDM;
            if (prev != ZERO && prev != ONE)
                printf("%08lx: new-data marker\n", a - 2);
            fread(buf, 1, 18, fp);
            if (buf[0] == MPULSE && buf[1] == SPULSE)
                b |= 0x01;
            if (buf[2] == MPULSE && buf[3] == SPULSE)
                b |= 0x02;
            if (buf[4] == MPULSE && buf[5] == SPULSE)
                b |= 0x04;
            if (buf[6] == MPULSE && buf[7] == SPULSE)
                b |= 0x08;
            if (buf[8] == MPULSE && buf[9] == SPULSE)
                b |= 0x10;
            if (buf[10] == MPULSE && buf[11] == SPULSE)
                b |= 0x20;
            if (buf[12] == MPULSE && buf[13] == SPULSE)
                b |= 0x40;
            if (buf[14] == MPULSE && buf[15] == SPULSE)
                b |= 0x80;
            if (buf[16] == MPULSE && buf[17] == SPULSE)
                p = 1;
            if (p)
                curr = ONE;
            else
                curr = ZERO;
            assert(p == (1 ^ parity(b)));
            printf("%08lx: %02x  ", a, b);
            if (b >= 0x20 && b < 0x7f)
                putchar(b);
            printf("\n");
        } else if (buf[0] == LPULSE && buf[1] == SPULSE) {
            curr = ENDDM;
            printf("%08lx: end-of-data marker\n", ftell(fp) - 2);
        } else if (buf[0] == 0x00) {
            unsigned long a = ftell(fp) - 2;
            fread(buf + 2, 1, 2, fp);
            int plen = 65536 * buf[3] + 256 * buf[2] + buf[1];
            printf("%08lx: pulse = %d\n", a, plen);
        } else {
            if (buf[0] == SPULSE && prev == PILOT) {
                printf("%08lx: %02x %02x unknown resyncing\n",
                       ftell(fp) - 2, buf[0] & 0xff, buf[1] & 0xff);
                fseek(fp, -3, SEEK_CUR);
            } else {
                printf("%08lx: %02x %02x unknown\n",
                       ftell(fp) - 2, buf[0] & 0xff, buf[1] & 0xff);
            }
        }
        prev = curr;
    }

    fclose(fp);
}
